openapi: 3.0.3
info:
  title: Todo Task Management API
  description: RESTful API for managing todo tasks with JWT authentication and user data isolation
  version: 1.0.0
  contact:
    name: Todo App Team

servers:
  - url: http://localhost:8080
    description: Local development server

security:
  - BearerAuth: []

tags:
  - name: Tasks
    description: Task CRUD operations

paths:
  /api/tasks:
    get:
      summary: List all tasks for authenticated user
      description: Returns all tasks belonging to the authenticated user, ordered by creation date (newest first)
      tags:
        - Tasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved task list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
              example:
                - id: "550e8400-e29b-41d4-a716-446655440000"
                  user_id: "123e4567-e89b-12d3-a456-426614174000"
                  title: "Buy groceries"
                  description: "Milk, eggs, bread"
                  completed: false
                  completed_at: null
                  created_at: "2026-02-08T12:00:00Z"
                  updated_at: "2026-02-08T12:00:00Z"
                - id: "660e8400-e29b-41d4-a716-446655440001"
                  user_id: "123e4567-e89b-12d3-a456-426614174000"
                  title: "Complete project report"
                  description: "Include Q4 metrics"
                  completed: true
                  completed_at: "2026-02-08T11:30:00Z"
                  created_at: "2026-02-08T10:00:00Z"
                  updated_at: "2026-02-08T11:30:00Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      summary: Create a new task
      description: Creates a new task for the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            example:
              title: "Buy groceries"
              description: "Milk, eggs, bread"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: false
                completed_at: null
                created_at: "2026-02-08T12:00:00Z"
                updated_at: "2026-02-08T12:00:00Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/ValidationError'

  /api/tasks/{task_id}:
    get:
      summary: Get a specific task by ID
      description: Returns a single task if it belongs to the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Successfully retrieved task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: false
                completed_at: null
                created_at: "2026-02-08T12:00:00Z"
                updated_at: "2026-02-08T12:00:00Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/ValidationError'

    put:
      summary: Update a task
      description: Updates title and/or description of an existing task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            example:
              title: "Buy groceries and cook dinner"
              description: "Milk, eggs, bread, chicken"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                title: "Buy groceries and cook dinner"
                description: "Milk, eggs, bread, chicken"
                completed: false
                completed_at: null
                created_at: "2026-02-08T12:00:00Z"
                updated_at: "2026-02-08T12:05:00Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      summary: Delete a task
      description: Permanently deletes a task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/ValidationError'

  /api/tasks/{task_id}/complete:
    patch:
      summary: Toggle task completion status
      description: Marks an incomplete task as complete (with timestamp) or a complete task as incomplete (clearing timestamp)
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              examples:
                marked_complete:
                  summary: Task marked as complete
                  value:
                    id: "550e8400-e29b-41d4-a716-446655440000"
                    user_id: "123e4567-e89b-12d3-a456-426614174000"
                    title: "Buy groceries"
                    description: "Milk, eggs, bread"
                    completed: true
                    completed_at: "2026-02-08T12:10:00Z"
                    created_at: "2026-02-08T12:00:00Z"
                    updated_at: "2026-02-08T12:10:00Z"
                marked_incomplete:
                  summary: Task marked as incomplete
                  value:
                    id: "550e8400-e29b-41d4-a716-446655440000"
                    user_id: "123e4567-e89b-12d3-a456-426614174000"
                    title: "Buy groceries"
                    description: "Milk, eggs, bread"
                    completed: false
                    completed_at: null
                    created_at: "2026-02-08T12:00:00Z"
                    updated_at: "2026-02-08T12:15:00Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/ValidationError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from authentication endpoints

  parameters:
    TaskId:
      name: task_id
      in: path
      required: true
      description: UUID of the task
      schema:
        type: string
        format: uuid
      example: "550e8400-e29b-41d4-a716-446655440000"

  schemas:
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title (required, non-empty)
          example: "Buy groceries"
        description:
          type: string
          maxLength: 2000
          description: Optional task description
          example: "Milk, eggs, bread"
          default: ""

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Updated task title
          example: "Buy groceries and cook dinner"
        description:
          type: string
          maxLength: 2000
          description: Updated task description
          example: "Milk, eggs, bread, chicken"

    TaskResponse:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        user_id:
          type: string
          format: uuid
          description: Owner of the task
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          description: Task description (optional)
          example: "Milk, eggs, bread"
        completed:
          type: boolean
          description: Completion status
          example: false
        completed_at:
          type: string
          format: date-time
          nullable: true
          description: When task was marked complete (null if incomplete)
          example: "2026-02-08T12:10:00Z"
        created_at:
          type: string
          format: date-time
          description: When task was created
          example: "2026-02-08T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: When task was last modified
          example: "2026-02-08T12:00:00Z"

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task not found"

    ValidationError:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                description: Location of the error
              msg:
                type: string
                description: Error message
              type:
                type: string
                description: Error type

  responses:
    UnauthorizedError:
      description: Missing or invalid JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Could not validate credentials"

    ForbiddenError:
      description: Task belongs to another user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Access denied"

    NotFoundError:
      description: Task not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Task not found"

    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
          example:
            detail:
              - loc: ["body", "title"]
                msg: "Title cannot be empty or whitespace only"
                type: "value_error"
